/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pkg01.proyectofinal;

import java.awt.Container;
import java.awt.Dimension;
import java.awt.Graphics;
import java.awt.Image;
import java.net.URL;
import java.util.ArrayList;
import javax.swing.ImageIcon;

/**
 *
 * @author gillian
 */
public class NuevoHeroe extends java.awt.Frame {

//    public class Imagen extends java.awt.Frame {
//
//        public Imagen() {
//            this.setSize(100, 100);
//
//        }
//
//        public void paint(Graphics grafico) {
//            Dimension height = getSize();
//            ImageIcon Img = new ImageIcon(getClass().getResource("/Imagenes/GUERRERO.png"));
//            grafico.drawImage(Img.getImage(), 0, 0, height.width, height.height, null);
////setOpaque(false);
////super.paintComponent(grafico);
//        }
//    }
    public Image ImagenFondo;
    public URL fondo;

    /**
     * Creates new form NuevoHeroe
     */
    public NuevoHeroe() {
        initComponents();
//        --------Valores del choice----------------------
        choiceProfesion.add("");
        choiceProfesion.add("Guerrero");
        choiceProfesion.add("Mago");
        choiceProfesion.add("Bestia");
        choiceProfesion.add("Asesino");
        choiceProfesion.add("Arquero");
        choiceProfesion.add("Sacerdote");
//        -------------Evitar que se seleccione mas de 2 checkbox----------------------
        

//        fondo= this.getClass().getResource("/Imagenes/GUERRERO.png");
//        ImagenFondo= new ImageIcon(fondo).getImage();
//        
//        Container contenedor = getContentPane();
//        contenedor.add(PanelSkin);
    }

//    public void paintComponent(Graphics g){
//        g.drawImage(ImagenFondo, 0, 0, getWidth(), getHeight(),this);
//    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();
        PanelSkin = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        TFNombre = new javax.swing.JTextField();
        choiceProfesion = new java.awt.Choice();
        BGuardar = new javax.swing.JButton();
        CBFuego = new javax.swing.JCheckBox();
        CBAgua = new javax.swing.JCheckBox();
        CBViento = new javax.swing.JCheckBox();
        CBMetal = new javax.swing.JCheckBox();
        CBTierra = new javax.swing.JCheckBox();
        CBTrueno = new javax.swing.JCheckBox();
        SliderCOR = new javax.swing.JSlider();
        SliderINT = new javax.swing.JSlider();
        SliderFUE = new javax.swing.JSlider();
        SliderAGI = new javax.swing.JSlider();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        BCancelar = new javax.swing.JButton();
        BSalir = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        BSkin = new javax.swing.JButton();
        Bpuntos = new javax.swing.JButton();
        Bcorazon = new javax.swing.JButton();
        Binteligencia = new javax.swing.JButton();
        Bfuerza = new javax.swing.JButton();
        Bagilidad = new javax.swing.JButton();

        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                exitForm(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Rosewood Std Regular", 0, 36)); // NOI18N
        jLabel1.setText("Crear Nuevo Heroe");

        PanelSkin.setBackground(new java.awt.Color(51, 51, 51));
        PanelSkin.addContainerListener(new java.awt.event.ContainerAdapter() {
            public void componentAdded(java.awt.event.ContainerEvent evt) {
                PanelSkinComponentAdded(evt);
            }
        });

        jLabel2.setText("Nombre:");

        jLabel3.setText("Profesion:");

        BGuardar.setText("Guardar");
        BGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BGuardarActionPerformed(evt);
            }
        });

        CBFuego.setText("Fuego");

        CBAgua.setText("Agua");

        CBViento.setText("Viento");

        CBMetal.setText("Metal");

        CBTierra.setText("Tierra");

        CBTrueno.setText("Trueno");

        SliderCOR.setMajorTickSpacing(1);
        SliderCOR.setMaximum(15);
        SliderCOR.setPaintTicks(true);
        SliderCOR.setValue(0);
        SliderCOR.setEnabled(false);
        SliderCOR.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                SliderCORStateChanged(evt);
            }
        });

        SliderINT.setMajorTickSpacing(1);
        SliderINT.setMaximum(15);
        SliderINT.setPaintTicks(true);
        SliderINT.setValue(0);
        SliderINT.setEnabled(false);

        SliderFUE.setMajorTickSpacing(1);
        SliderFUE.setMaximum(10);
        SliderFUE.setPaintTicks(true);
        SliderFUE.setValue(0);
        SliderFUE.setEnabled(false);

        SliderAGI.setMajorTickSpacing(1);
        SliderAGI.setMaximum(10);
        SliderAGI.setPaintTicks(true);
        SliderAGI.setValue(0);
        SliderAGI.setEnabled(false);

        jLabel4.setFont(new java.awt.Font("Old English Text MT", 0, 18)); // NOI18N
        jLabel4.setText("Corazon");

        jLabel5.setFont(new java.awt.Font("Old English Text MT", 0, 18)); // NOI18N
        jLabel5.setText("Inteligencia");

        jLabel6.setFont(new java.awt.Font("Old English Text MT", 0, 18)); // NOI18N
        jLabel6.setText("Fuerza");

        jLabel7.setFont(new java.awt.Font("Old English Text MT", 0, 18)); // NOI18N
        jLabel7.setText("Agilidad ");

        BCancelar.setText("Cancelar");

        BSalir.setText("Salir");

        jLabel9.setText("Puntos:");

        BSkin.setText("Skin");
        BSkin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BSkinActionPerformed(evt);
            }
        });

        Bpuntos.setText("20");
        Bpuntos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BpuntosActionPerformed(evt);
            }
        });

        Bcorazon.setText("0");
        Bcorazon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BcorazonActionPerformed(evt);
            }
        });

        Binteligencia.setText("0");
        Binteligencia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BinteligenciaActionPerformed(evt);
            }
        });

        Bfuerza.setText("0");
        Bfuerza.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BfuerzaActionPerformed(evt);
            }
        });

        Bagilidad.setText("0");
        Bagilidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BagilidadActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jSeparator1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(jLabel1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(PanelSkin, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(23, 23, 23)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel7)
                                    .addComponent(BGuardar)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(BSkin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(24, 24, 24)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel2))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addComponent(TFNombre))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addComponent(choiceProfesion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(SliderAGI, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(Bagilidad))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(SliderFUE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(Bfuerza))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(SliderCOR, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(SliderINT, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(Bcorazon)
                                            .addComponent(Binteligencia)))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(155, 155, 155)
                                        .addComponent(jLabel9)
                                        .addGap(18, 18, 18)
                                        .addComponent(Bpuntos))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(CBFuego)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(CBAgua))
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(CBMetal)
                                                .addGap(28, 28, 28)
                                                .addComponent(CBTierra)))
                                        .addGap(18, 18, 18)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(CBTrueno)
                                            .addComponent(CBViento))))
                                .addGap(14, 14, 14))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(46, 46, 46)
                                .addComponent(BCancelar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(BSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(28, 28, 28)))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(TFNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(choiceProfesion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(CBFuego)
                            .addComponent(CBAgua)
                            .addComponent(CBViento))
                        .addGap(9, 9, 9)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(CBMetal)
                            .addComponent(CBTierra)
                            .addComponent(CBTrueno))
                        .addGap(5, 5, 5)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(Bpuntos)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(PanelSkin, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(BSkin)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(SliderCOR, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(Bcorazon, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(SliderINT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(Binteligencia, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(SliderFUE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(Bfuerza, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(SliderAGI, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(Bagilidad, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 11, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BGuardar)
                    .addComponent(BCancelar)
                    .addComponent(BSalir))
                .addGap(20, 20, 20))
        );

        add(jPanel1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Exit the Application
     */
    private void exitForm(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_exitForm
        System.exit(0);
    }//GEN-LAST:event_exitForm

    private void SliderCORStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_SliderCORStateChanged
        // TODO add your handling code here:
//        LabelCorazon.setText(""+SliderCOR.getValue());
//        int corazon=SliderCOR.getValue();
//        int puntosD = Integer.parseInt(LabelPuntos.getText());
//        int puntosU = Integer.parseInt(LabelCorazon.getText());
//        System.out.println("puntos = "+puntosD+" + "+ puntosU);
//       
//        if(puntosD!=puntosU){
//            LabelCorazon.setText("" +corazon);
//            puntosD=puntosD-corazon;
//            LabelPuntos.setText(""+puntosD);
//            if(puntosD<puntosU){
//                SliderCOR.setValue(20);
//                puntosD=0;
//                System.out.println("puntos dados = "+puntosD);
//                LabelPuntos.setText(""+puntosD);     
//            }
//        }
//        if(puntos!=0){
//            puntos=puntos-corazon;
//            SliderCOR.setMaximum(20);
//        } 
//        LabelPuntos.setText(""+puntos); 
//         SliderCOR.setMaximum(puntos);


    }//GEN-LAST:event_SliderCORStateChanged

    private void BcorazonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BcorazonActionPerformed
        // TODO add your handling code here:
        int COR = Integer.parseInt(Bcorazon.getText());
        int INT = Integer.parseInt(Binteligencia.getText());
        int FUE = Integer.parseInt(Bfuerza.getText());
        int AGI = Integer.parseInt(Bagilidad.getText());

        int puntos = Integer.parseInt(Bpuntos.getText());
//        System.out.println("puntos = "+COR);
        if (COR <= 9) {
            if ((COR + INT + FUE + AGI) <= 19) {
                puntos = puntos - 1;
                COR = COR + 1;
                SliderCOR.setValue(COR);
                Bcorazon.setText("" + COR);
                Bpuntos.setText("" + puntos);
            }
        }


    }//GEN-LAST:event_BcorazonActionPerformed

    private void BinteligenciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BinteligenciaActionPerformed
        // TODO add your handling code here:
        int COR = Integer.parseInt(Bcorazon.getText());
        int INT = Integer.parseInt(Binteligencia.getText());
        int FUE = Integer.parseInt(Bfuerza.getText());
        int AGI = Integer.parseInt(Bagilidad.getText());

        int puntos = Integer.parseInt(Bpuntos.getText());
//        System.out.println("puntos = "+INT);
        if (INT <= 9) {
            if ((COR + INT + FUE + AGI) <= 19) {
                puntos = puntos - 1;
                INT = INT + 1;
                SliderINT.setValue(INT);
                Binteligencia.setText("" + INT);
                Bpuntos.setText("" + puntos);
            }
        }
    }//GEN-LAST:event_BinteligenciaActionPerformed

    private void BfuerzaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BfuerzaActionPerformed
        // TODO add your handling code here:
        int COR = Integer.parseInt(Bcorazon.getText());
        int INT = Integer.parseInt(Binteligencia.getText());
        int FUE = Integer.parseInt(Bfuerza.getText());
        int AGI = Integer.parseInt(Bagilidad.getText());

        int puntos = Integer.parseInt(Bpuntos.getText());
//        System.out.println("puntos = "+FUE);
        if (FUE <= 9) {
            if ((COR + INT + FUE + AGI) <= 19) {
                puntos = puntos - 1;
                FUE = FUE + 1;
                SliderFUE.setValue(FUE);
                Bfuerza.setText("" + FUE);
                Bpuntos.setText("" + puntos);
            }
        }
    }//GEN-LAST:event_BfuerzaActionPerformed

    private void BagilidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BagilidadActionPerformed
        // TODO add your handling code here:
        int COR = Integer.parseInt(Bcorazon.getText());
        int INT = Integer.parseInt(Binteligencia.getText());
        int FUE = Integer.parseInt(Bfuerza.getText());
        int AGI = Integer.parseInt(Bagilidad.getText());

        int puntos = Integer.parseInt(Bpuntos.getText());
//        System.out.println("puntos = "+AGI);
        if (AGI <= 9) {
            if ((COR + INT + FUE + AGI) <= 19) {
                puntos = puntos - 1;
                AGI = AGI + 1;
                SliderAGI.setValue(AGI);
                Bagilidad.setText("" + AGI);
                Bpuntos.setText("" + puntos);
            }
        }
    }//GEN-LAST:event_BagilidadActionPerformed

    private void BpuntosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BpuntosActionPerformed
        // TODO add your handling code here:

        SliderCOR.setValue(0);
        SliderAGI.setValue(0);
        SliderFUE.setValue(0);
        SliderINT.setValue(0);

        Bagilidad.setText("" + 0);
        Bcorazon.setText("" + 0);
        Binteligencia.setText("" + 0);
        Bfuerza.setText("" + 0);

        Bpuntos.setText("" + 20);
    }//GEN-LAST:event_BpuntosActionPerformed

    private void BSkinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BSkinActionPerformed
        // TODO add your handling code here:
//        Imagen Imagen = new Imagen();
//        PanelSkin.add(Imagen);
//        PanelSkin.repaint();
    }//GEN-LAST:event_BSkinActionPerformed

    private void PanelSkinComponentAdded(java.awt.event.ContainerEvent evt) {//GEN-FIRST:event_PanelSkinComponentAdded
        // TODO add your handling code here:

    }//GEN-LAST:event_PanelSkinComponentAdded

    private void BGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BGuardarActionPerformed
        // TODO add your handling code here:
        int Ataque = 0;
        int Vida = 0;
        double vel = 0;
        String Nombre = TFNombre.getText();
        String Ruta = PrincipalRPG.RutaBase + PrincipalRPG.RutaUser;
        String Archivo = Nombre + ".txt";
        ArrayList Contenido = new ArrayList();

        Contenido.add(Nombre);
        Contenido.add(choiceProfesion.getSelectedItem());

        int COR = Integer.parseInt(Bcorazon.getText());
        int INT = Integer.parseInt(Binteligencia.getText());
        int FUE = Integer.parseInt(Bfuerza.getText());
        double AGI = Integer.parseInt(Bagilidad.getText());

//------------------------Calculando Ataque y vida----------------------------------         
        if (choiceProfesion.getSelectedItem().equals("Guerrero")) {
            FUE = FUE * 100;
            INT = INT * 50;
            Ataque = 200 + COR + INT;
            COR = COR * 100;
            Vida = 1000 + COR;
            AGI = AGI * (0.1);
            vel = 5 + AGI;

        }
        if (choiceProfesion.getSelectedItem().equals("Mago")) {
            FUE=FUE*(-100);
            INT=INT*100;
            Ataque = 300+FUE+INT;
            COR=COR*50;
            Vida = 800+COR;
            AGI=AGI*0.05;
            vel = 4+AGI;

        }
        if (choiceProfesion.getSelectedItem().equals("Bestia")) {
            FUE=FUE*120;
            INT=INT*(-100);
            Ataque = 250+FUE+INT;
            COR=COR*50;
            Vida = 900+COR;
            AGI=AGI*0.01;
            vel = 3+AGI;
        }
        if (choiceProfesion.getSelectedItem().equals("Asesino")) {
            FUE=FUE+50;
            INT=INT+50;
            Ataque = 100+FUE+INT;
            COR=COR*100;
            Vida = 1000+COR;
            AGI=AGI*0.5;
            vel = 7+AGI;
        }
        if (choiceProfesion.getSelectedItem().equals("Arquero")) {
            FUE=FUE*100;
            INT=INT*(-50);
            Ataque = 200+FUE+INT;
            COR=COR*100;
            Vida = 900+COR;
            AGI=AGI*0.3;
            vel = 6+AGI;
        }
        if (choiceProfesion.getSelectedItem().equals("Sacerdote")) {
            FUE=FUE*50;
            INT=INT*50;
            Ataque = 150+FUE+INT;
            COR=COR*200;
            Vida = 1200+COR;
            AGI=AGI*0.02;
            vel = 4+AGI;
        }
        Contenido.add("1");
        Contenido.add(Ataque);
        Contenido.add(Vida);
        Contenido.add(vel);
        Contenido.add("0");

        Archivos.TextFiles.writeFilePlus(Ruta, Archivo, Contenido);

    }//GEN-LAST:event_BGuardarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NuevoHeroe().setVisible(true);
            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BCancelar;
    private javax.swing.JButton BGuardar;
    private javax.swing.JButton BSalir;
    private javax.swing.JButton BSkin;
    private javax.swing.JButton Bagilidad;
    private javax.swing.JButton Bcorazon;
    private javax.swing.JButton Bfuerza;
    private javax.swing.JButton Binteligencia;
    private javax.swing.JButton Bpuntos;
    private javax.swing.JCheckBox CBAgua;
    private javax.swing.JCheckBox CBFuego;
    private javax.swing.JCheckBox CBMetal;
    private javax.swing.JCheckBox CBTierra;
    private javax.swing.JCheckBox CBTrueno;
    private javax.swing.JCheckBox CBViento;
    private javax.swing.JPanel PanelSkin;
    private javax.swing.JSlider SliderAGI;
    private javax.swing.JSlider SliderCOR;
    private javax.swing.JSlider SliderFUE;
    private javax.swing.JSlider SliderINT;
    private javax.swing.JTextField TFNombre;
    private java.awt.Choice choiceProfesion;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    // End of variables declaration//GEN-END:variables
}
