/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pkg01.proyectofinal;

import java.io.IOException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author gillian
 */
public class Principal extends java.awt.Frame {

    static String rutaBase = "C:\\Users\\gillian\\Desktop\\GAME\\RPG bac\\";
    ArrayList statusH = new ArrayList();
    

    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
        Desabilitar();
        ChoicePro.add("");
        ChoicePro.add("Guerrero");
        ChoicePro.add("Mago");
        ChoicePro.add("Arquero");
        Llenar();

    }

    void Desabilitar() {
        TFNombre.setEditable(false);
        ChoicePro.setEnabled(false);
        checkboxEsp.setEnabled(false);
        checkboxBas.setEnabled(false);
        BOk.setEnabled(false);
//        BLvl.setEnabled(false);
//        BDañar.setEnabled(false);
    }

    void Habilitar() {
        TFNombre.setEditable(true);
        ChoicePro.setEnabled(true);
        checkboxEsp.setEnabled(true);
        checkboxBas.setEnabled(true);
        BOk.setEnabled(true);
//        BLvl.setEnabled(true);
//        BDañar.setEnabled(true);
    }
//-----------------------------------------------------------------------------------------------------------
//-----------------------------------------------------------------------------------------------------------    

    void Llenar() {
        String archivo = "Status Heroe.txt";
        ArrayList contenido = new ArrayList();
//---------------LLenar datos del Heroe...-----------------------------------------------------------
        boolean existe = false;
        existe = Archivos.TextFiles.existFiles(rutaBase, archivo);
        if (existe) {
            try {

                statusH = Archivos.TextFiles.readFile(rutaBase, archivo);
                for (int i = 0; i < statusH.size(); i++) {
                    contenido.add(statusH.get(i));
                }
                TFHeroe.setText(contenido.get(0).toString());
                TFProfecion.setText(contenido.get(1).toString());
                TFNivel.setText(contenido.get(2).toString());
                TFAtaque.setText(contenido.get(3).toString());
                TFVida.setText(contenido.get(4).toString());
                TFExp.setText(contenido.get(5).toString());
                LabelExp.setText(contenido.get(6).toString());
                
            } catch (IOException ex) {
                Logger.getLogger(Principal.class.getName()).log(Level.SEVERE, null, ex);
            }

        }
        Habilitar();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel1 = new java.awt.Panel();
        label1 = new java.awt.Label();
        label2 = new java.awt.Label();
        TFNombre = new java.awt.TextField();
        ChoicePro = new java.awt.Choice();
        checkboxEsp = new java.awt.Checkbox();
        checkboxBas = new java.awt.Checkbox();
        BOk = new java.awt.Button();
        listaEventos = new java.awt.List();
        jSeparator1 = new javax.swing.JSeparator();
        TFHeroe = new java.awt.TextField();
        TFAtaque = new java.awt.TextField();
        TFVida = new java.awt.TextField();
        label3 = new java.awt.Label();
        label4 = new java.awt.Label();
        label5 = new java.awt.Label();
        label6 = new java.awt.Label();
        TFNivel = new java.awt.TextField();
        label7 = new java.awt.Label();
        TFExp = new java.awt.TextField();
        BLvl = new java.awt.Button();
        BDañar = new java.awt.Button();
        BEliminar = new java.awt.Button();
        TFProfecion = new java.awt.TextField();
        jLabel1 = new javax.swing.JLabel();
        LabelExp = new javax.swing.JLabel();
        menuBar1 = new java.awt.MenuBar();
        menu1 = new java.awt.Menu();
        menu2 = new java.awt.Menu();

        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                exitForm(evt);
            }
        });

        panel1.setBackground(new java.awt.Color(0, 0, 0));

        label1.setFont(new java.awt.Font("Felix Titling", 0, 12)); // NOI18N
        label1.setForeground(new java.awt.Color(255, 255, 255));
        label1.setText("Nombre:");

        label2.setForeground(new java.awt.Color(255, 255, 255));
        label2.setText("Profesion:");

        checkboxEsp.setForeground(new java.awt.Color(255, 255, 255));
        checkboxEsp.setLabel("Espada");

        checkboxBas.setForeground(new java.awt.Color(255, 255, 255));
        checkboxBas.setLabel("Baston");

        BOk.setLabel("OK");
        BOk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BOkActionPerformed(evt);
            }
        });

        TFHeroe.setEditable(false);

        TFAtaque.setEditable(false);

        TFVida.setEditable(false);

        label3.setFont(new java.awt.Font("Felix Titling", 1, 12)); // NOI18N
        label3.setForeground(new java.awt.Color(255, 255, 255));
        label3.setText("HEROE:");

        label4.setForeground(new java.awt.Color(255, 255, 255));
        label4.setText("Ataque:");

        label5.setForeground(new java.awt.Color(255, 0, 0));
        label5.setText("Vida:");

        label6.setForeground(new java.awt.Color(255, 255, 255));
        label6.setText("Nivel:");

        TFNivel.setEditable(false);

        label7.setForeground(new java.awt.Color(255, 255, 255));
        label7.setText("Experiencia:");

        TFExp.setEditable(false);
        TFExp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TFExpActionPerformed(evt);
            }
        });

        BLvl.setLabel("Lvl");
        BLvl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BLvlActionPerformed(evt);
            }
        });

        BDañar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        BDañar.setLabel("Dañar");
        BDañar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BDañarActionPerformed(evt);
            }
        });

        BEliminar.setLabel("Nuevo Heroe");
        BEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BEliminarActionPerformed(evt);
            }
        });

        TFProfecion.setEditable(false);

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Profesion:");

        LabelExp.setForeground(new java.awt.Color(255, 255, 255));
        LabelExp.setText("100");

        javax.swing.GroupLayout panel1Layout = new javax.swing.GroupLayout(panel1);
        panel1.setLayout(panel1Layout);
        panel1Layout.setHorizontalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel1Layout.createSequentialGroup()
                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(listaEventos, javax.swing.GroupLayout.PREFERRED_SIZE, 360, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(panel1Layout.createSequentialGroup()
                            .addGap(22, 22, 22)
                            .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(panel1Layout.createSequentialGroup()
                                    .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(label2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGap(22, 22, 22)
                                    .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(TFNombre, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(ChoicePro, javax.swing.GroupLayout.DEFAULT_SIZE, 146, Short.MAX_VALUE))
                                    .addGap(34, 34, 34)
                                    .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(checkboxBas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(checkboxEsp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addComponent(BOk, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(panel1Layout.createSequentialGroup()
                            .addContainerGap()
                            .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 368, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panel1Layout.createSequentialGroup()
                                    .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(BEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(panel1Layout.createSequentialGroup()
                                            .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                    .addComponent(TFAtaque, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                    .addComponent(label3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addComponent(label4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(BLvl, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(TFHeroe, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGroup(panel1Layout.createSequentialGroup()
                                                    .addGap(10, 10, 10)
                                                    .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(TFVida, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(BDañar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(label5, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                            .addGap(35, 35, 35)
                                            .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(label7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                    .addComponent(TFProfecion, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panel1Layout.createSequentialGroup()
                                                        .addComponent(label6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                        .addComponent(TFNivel, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                .addComponent(jLabel1)
                                                .addComponent(TFExp, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(LabelExp))))))
                .addContainerGap(21, Short.MAX_VALUE))
        );
        panel1Layout.setVerticalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TFNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(checkboxEsp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(label2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ChoicePro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(checkboxBas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BOk, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel1Layout.createSequentialGroup()
                        .addGap(150, 150, 150)
                        .addComponent(LabelExp)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(label3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TFHeroe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(label6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TFNivel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(label4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(label5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(TFAtaque, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(TFVida, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(TFProfecion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(20, 20, 20)
                        .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(label7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(BLvl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(BDañar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(TFExp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addComponent(BEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(listaEventos, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34))
        );

        menu1.setLabel("File");
        menuBar1.add(menu1);

        menu2.setLabel("Edit");
        menuBar1.add(menu2);

        setMenuBar(menuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Exit the Application
     */
    private void exitForm(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_exitForm
        System.exit(0);
    }//GEN-LAST:event_exitForm

    private void BEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BEliminarActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null, "Se Eliminaron los datos del Heroe anterior.");
        String heroe=TFHeroe.getText();
        TFHeroe.setText("");
        TFProfecion.setText("");
        TFNivel.setText("");
        TFAtaque.setText("");
        TFVida.setText("");
        TFExp.setText("");
        LabelExp.setText("100");
        String archivo = "Status Heroe.txt";
        Archivos.TextFiles.deleteFiles(rutaBase, archivo);
        Habilitar();
        listaEventos.add("A Eliminado al Heroe llamado "+heroe);
    }//GEN-LAST:event_BEliminarActionPerformed

    private void BDañarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BDañarActionPerformed
        // TODO add your handling code here:
        //----- Resptar vida hasta eliminar al heroe.......
        String archivo = "Status Heroe.txt";
        ArrayList contenido = new ArrayList();
        Archivos.TextFiles.deleteFiles(rutaBase, archivo);

        int daño = 100;
        //        String nom=TFHeroe.getText();
        //        String pro=TFProfecion.getText();
        //        String niv=TFNivel.getText();
        //        String ata=TFAtaque.getText();
        int vida = Integer.parseInt(TFVida.getText());
        //        String exp= TFExp.getText();
        //        String nlvl=LabelExp.getText();
        vida = vida - daño;
        listaEventos.add(TFHeroe.getText()+" a recivido "+daño+" puntos de daño");
        if (vida <= 0) {
            JOptionPane.showMessageDialog(null, "El Heroe a sido Eliminado");
            listaEventos.add("El Heroe "+TFHeroe.getText()+" a perdido todos sus puntos de vida");
            //            BLvl.setEnabled(false);
            //        BDañar.setEnabled(false);
        }
        contenido.add(TFHeroe.getText());
        contenido.add(TFProfecion.getText());
        contenido.add(TFNivel.getText());
        contenido.add(TFAtaque.getText());
        contenido.add(Integer.toString(vida));
        contenido.add(TFExp.getText());
        contenido.add(LabelExp.getText());

        Archivos.TextFiles.writeFilePlus(rutaBase, archivo, contenido);
        Llenar();

    }//GEN-LAST:event_BDañarActionPerformed

    private void BLvlActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BLvlActionPerformed
        // TODO add your handling code here:
        String archivo = "Status Heroe.txt";
        ArrayList contenido = new ArrayList();
        Archivos.TextFiles.deleteFiles(rutaBase, archivo);

        int experiencia = 100;
        int nivorg = Integer.parseInt(TFNivel.getText());
        int nivel = Integer.parseInt(TFNivel.getText());
        System.out.println("el nivel es=" + nivel);
        int exp = Integer.parseInt(TFExp.getText());
        System.out.println("exp=" + exp);
        int ataque = Integer.parseInt(TFAtaque.getText());
        int vida = Integer.parseInt(TFVida.getText());
        //        String[] nlvl= LabelExp.getText().toString().split("/");
        int nextlvl = Integer.parseInt(LabelExp.getText());
        System.out.println("Siguiente nivel" + nextlvl);

        exp = exp + experiencia;
        listaEventos.add(TFHeroe.getText()+" a ganado "+exp+" puntos de experiencia");
        System.out.println("expp++" + exp);
        if (exp >= nextlvl) {
            nivel++;
            ataque = ataque + 100;
            vida = vida + 200;
            listaEventos.add(TFHeroe.getText()+" a subido al nivel "+nivel);
        }
        if (nivel > nivorg) {
            nextlvl = nextlvl * 2;
        }
        System.out.println("sig nivel= " + nextlvl);

        contenido.add(TFHeroe.getText());
        contenido.add(TFProfecion.getText());
        contenido.add(Integer.toString(nivel));
        contenido.add(Integer.toString(ataque));
        contenido.add(Integer.toString(vida));
        contenido.add(Integer.toString(exp));
        contenido.add(Integer.toString(nextlvl));

        Archivos.TextFiles.writeFilePlus(rutaBase, archivo, contenido);
        Llenar();

    }//GEN-LAST:event_BLvlActionPerformed

    private void TFExpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TFExpActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TFExpActionPerformed

    private void BOkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BOkActionPerformed
        // TODO add your handling code here:
        //Registrar al heroe....
        int ataque = 0;
        int vida = 0;
        //    Grabar en archivo los status del Heroe
        String archivo = "Status Heroe.txt";
        ArrayList contenido = new ArrayList();
        contenido.add(TFNombre.getText());
        contenido.add(ChoicePro.getSelectedItem());

        boolean vacio = false;
        if (TFNombre.getText().equals("")) {
            vacio = true;
        }

        //        if (checkboxEsp.getState()) {
            //            contenido.add("Equipo:Espada");
            //        }
        //        if (checkboxBas.getState()) {
            //            contenido.add("Equipo:Baston");
            //        }
        //------------------------Calculando Ataque y vida----------------------------------
        if (ChoicePro.getSelectedItem().equals("Guerrero")) {
            ataque = 150;
            vida = 1200;
            if (checkboxEsp.getState()) {
                ataque = ataque + 100;
            }
            if (checkboxBas.getState()) {
                ataque = ataque - 100;
            }
        }
        if (ChoicePro.getSelectedItem().equals("Mago")) {
            ataque = 100;
            vida = 1000;
            if (checkboxEsp.getState()) {
                ataque = ataque - 100;
            }
            if (checkboxBas.getState()) {
                ataque = ataque + 100;
            }
        }
        if (ChoicePro.getSelectedItem().equals("Arquero")) {
            ataque = 150;
            vida = 1100;
            if (checkboxEsp.getState()) {
                ataque = ataque + 50;
            }
            if (checkboxBas.getState()) {
                ataque = ataque - 0;
            }
        }
        contenido.add("1");
        contenido.add(ataque);
        contenido.add(vida);
        contenido.add("0");
        if (!vacio) {
            Archivos.TextFiles.writeFilePlus(rutaBase, archivo, contenido);
            TFHeroe.setText(TFNombre.getText());
            TFProfecion.setText(ChoicePro.getSelectedItem());
            TFNivel.setText("1");
            TFAtaque.setText("" + ataque);
            TFVida.setText("" + vida);
            TFExp.setText("0");

            Desabilitar();
            TFNombre.setText("");
            listaEventos.add("A registrado un nuevo Heroe llamado "+TFHeroe.getText());
            listaEventos.add("Profecion: "+ChoicePro.getSelectedItem());
            listaEventos.add("Equipamento: ");
            listaEventos.add("");
            listaEventos.add("");
        }
    }//GEN-LAST:event_BOkActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Button BDañar;
    private java.awt.Button BEliminar;
    private java.awt.Button BLvl;
    private java.awt.Button BOk;
    private java.awt.Choice ChoicePro;
    private javax.swing.JLabel LabelExp;
    private java.awt.TextField TFAtaque;
    private java.awt.TextField TFExp;
    private java.awt.TextField TFHeroe;
    private java.awt.TextField TFNivel;
    private java.awt.TextField TFNombre;
    private java.awt.TextField TFProfecion;
    private java.awt.TextField TFVida;
    private java.awt.Checkbox checkboxBas;
    private java.awt.Checkbox checkboxEsp;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JSeparator jSeparator1;
    private java.awt.Label label1;
    private java.awt.Label label2;
    private java.awt.Label label3;
    private java.awt.Label label4;
    private java.awt.Label label5;
    private java.awt.Label label6;
    private java.awt.Label label7;
    private java.awt.List listaEventos;
    private java.awt.Menu menu1;
    private java.awt.Menu menu2;
    private java.awt.MenuBar menuBar1;
    private java.awt.Panel panel1;
    // End of variables declaration//GEN-END:variables
}
